<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <IsPackable>false</IsPackable>
        <UserSecretsId>aspnet-DevTools.InfiniLore.InfiniBlazor.Blazor-5adf3190-2fbf-42f5-af8e-b3e6c2d010fb</UserSecretsId>
    </PropertyGroup>
    
    <ItemGroup>
      <ProjectReference Include="..\..\tests\CodeOfChaosTests.Shared\CodeOfChaosTests.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
      <PackageReference Include="InfiniLore.InfiniBlazor" />
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="Components\Pages\EmoteDataEditor\EmoteDataEditorPage.razor" />
    </ItemGroup>
    
</Project>
