<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <!-- Package metadata -->
        <PackageId>CodeOfChaos.Markdown.Editors</PackageId>
        <Description>Markdown Parsers for C# and DotNet</Description>
        <PackageTags>Markdown;Parsing;Library</PackageTags>
    </PropertyGroup>
    
  <ItemGroup>
      <PackageReference Include="CodeOfChaos.Extensions.MicrosoftLogging" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection" />
      <PackageReference Include="CodeOfChaos.Extensions.DependencyInjection.Generators">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>analyzers</IncludeAssets>
      </PackageReference>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\CodeOfChaos.Markdown.Shared\CodeOfChaos.Markdown.Shared.csproj" />
  </ItemGroup>
</Project>


